=== nadazairuniversityskikda/miniprojet_XML/club.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="nom" type="xs:string"/>
    <xs:element name="prenom" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="dateInscription" type="xs:date"/>
    <xs:element name="nomCategorie" type="xs:string"/>
    <xs:element name="nomConcours" type="xs:string"/>
    <xs:element name="dateConcours" type="xs:date"/>
    <xs:element name="idCategorieCible" type="xs:string"/>
    
    <xs:element name="complexite">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="5"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="tempsExecution">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="coefficient">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="1.0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="membre">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element ref="prenom"/>
                <xs:element ref="email"/>
                <xs:element ref="dateInscription"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="membres">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="membre" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nomCategorie"/>
                <xs:element ref="membres"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="category" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="participant">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="complexite"/>
                <xs:element ref="tempsExecution"/>
                <xs:element ref="coefficient"/>
            </xs:sequence>
            <xs:attribute name="idMembre" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="participants">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="participant" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="concours">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nomConcours"/>
                <xs:element ref="dateConcours"/>
                <xs:element ref="idCategorieCible"/>
                <xs:element ref="participants"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="concoursList">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="concours" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="clubInfoTech">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="categories"/>
                <xs:element ref="concoursList"/>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="keyCategorie">
            <xs:selector xpath="categories/category"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="keyMembre">
            <xs:selector xpath="categories/category/membres/membre"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="keyConcours">
            <xs:selector xpath="concoursList/concours"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:keyref name="refMembreParticipant" refer="keyMembre">
            <xs:selector xpath="concoursList/concours/participants/participant"/>
            <xs:field xpath="@idMembre"/>
        </xs:keyref>
    </xs:element>

</xs:schema>

=== nadazairuniversityskikda/miniprojet_XML/club.xml
<?xml version="1.0" encoding="UTF-8"?>
<clubInfoTech xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="club.xsd">
    <categories>
        <category id="CAT01">
            <nomCategorie>Intelligence Artificielle</nomCategorie>
            <membres>
                <membre id="M001">
                    <nom>ALI GUECHI</nom>
                    <prenom>NERIMANE</prenom>
                    <email>n.aliguechi@club.dz</email>
                    <dateInscription>2025-10-15</dateInscription>
                </membre>
                <membre id="M002">
                    <nom>AMMARI</nom>
                    <prenom>MOHAMED ALA EDDINE</prenom>
                    <email>m.ammari@club.dz</email>
                    <dateInscription>2025-10-15</dateInscription>
                </membre>
                <membre id="M003">
                    <nom>ARNANE</nom>
                    <prenom>DOUAA</prenom>
                    <email>d.arnane@club.dz</email>
                    <dateInscription>2025-10-16</dateInscription>
                </membre>
                <membre id="M004">
                    <nom>BECHIRI</nom>
                    <prenom>ABDERRAHMANE</prenom>
                    <email>a.bechiri@club.dz</email>
                    <dateInscription>2025-10-16</dateInscription>
                </membre>
                <membre id="M005">
                    <nom>BELGHIT</nom>
                    <prenom>MIADA</prenom>
                    <email>m.belghit@club.dz</email>
                    <dateInscription>2025-10-18</dateInscription>
                </membre>
                <membre id="M006">
                    <nom>BENHAMAID</nom>
                    <prenom>ASMA</prenom>
                    <email>a.benhamaid@club.dz</email>
                    <dateInscription>2025-10-20</dateInscription>
                </membre>
                <membre id="M007">
                    <nom>BENKASSA</nom>
                    <prenom>DJABEUR ABDERRAHMANE</prenom>
                    <email>d.benkassa@club.dz</email>
                    <dateInscription>2025-10-20</dateInscription>
                </membre>
                <membre id="M008">
                    <nom>BERDOUDI</nom>
                    <prenom>OUSSAMA</prenom>
                    <email>o.berdoudi@club.dz</email>
                    <dateInscription>2025-10-22</dateInscription>
                </membre>
                <membre id="M009">
                    <nom>BOUAFIA</nom>
                    <prenom>OUISSALE</prenom>
                    <email>o.bouafia@club.dz</email>
                    <dateInscription>2025-10-22</dateInscription>
                </membre>
                <membre id="M010">
                    <nom>BOUAKAZ</nom>
                    <prenom>WISSAL</prenom>
                    <email>w.bouakaz@club.dz</email>
                    <dateInscription>2025-10-22</dateInscription>
                </membre>
                <membre id="M011">
                    <nom>BOUAKKAZ</nom>
                    <prenom>AMINA</prenom>
                    <email>a.bouakkaz@club.dz</email>
                    <dateInscription>2025-10-25</dateInscription>
                </membre>
                <membre id="M012">
                    <nom>BOUCHAALI</nom>
                    <prenom>IMANE</prenom>
                    <email>i.bouchaali@club.dz</email>
                    <dateInscription>2025-10-25</dateInscription>
                </membre>
                <membre id="M013">
                    <nom>BOUGRIRES</nom>
                    <prenom>ABIR</prenom>
                    <email>a.bougrires@club.dz</email>
                    <dateInscription>2025-10-26</dateInscription>
                </membre>
                <membre id="M014">
                    <nom>BOUTABA</nom>
                    <prenom>MOHAMED EL AMINE</prenom>
                    <email>m.boutaba@club.dz</email>
                    <dateInscription>2025-10-26</dateInscription>
                </membre>
                <membre id="M015">
                    <nom>BAAMEUR CHIKH</nom>
                    <prenom>SALAH EDDINE</prenom>
                    <email>s.baameurchikh@club.dz</email>
                    <dateInscription>2025-11-01</dateInscription>
                </membre>
                <membre id="M016">
                    <nom>BICI</nom>
                    <prenom>MOHAMED NAZIM</prenom>
                    <email>m.bici@club.dz</email>
                    <dateInscription>2025-11-01</dateInscription>
                </membre>
            </membres>
        </category>

        <category id="CAT02">
            <nomCategorie>Développement Web</nomCategorie>
            <membres>
                <membre id="M017">
                    <nom>BOUAFIA</nom>
                    <prenom>RANIA MILAD</prenom>
                    <email>r.bouafia@club.dz</email>
                    <dateInscription>2025-11-02</dateInscription>
                </membre>
                <membre id="M018">
                    <nom>BOUCHAREB</nom>
                    <prenom>WAIL ABD EL RAOUF</prenom>
                    <email>w.bouchareb@club.dz</email>
                    <dateInscription>2025-11-02</dateInscription>
                </membre>
                <membre id="M019">
                    <nom>BOUCHERKA</nom>
                    <prenom>SELSEBIL</prenom>
                    <email>s.boucherka@club.dz</email>
                    <dateInscription>2025-11-03</dateInscription>
                </membre>
                <membre id="M020">
                    <nom>BOUDEKHANA</nom>
                    <prenom>ANFAL</prenom>
                    <email>a.boudekhana@club.dz</email>
                    <dateInscription>2025-11-03</dateInscription>
                </membre>
                <membre id="M021">
                    <nom>BOUGAMOUZA</nom>
                    <prenom>MOHAMED EL MEHDI</prenom>
                    <email>m.bougamouza@club.dz</email>
                    <dateInscription>2025-11-05</dateInscription>
                </membre>
                <membre id="M022">
                    <nom>BOUKEBIR</nom>
                    <prenom>HANA</prenom>
                    <email>h.boukebir@club.dz</email>
                    <dateInscription>2025-11-05</dateInscription>
                </membre>
                <membre id="M023">
                    <nom>BOURIA</nom>
                    <prenom>TEIMA</prenom>
                    <email>t.bouria@club.dz</email>
                    <dateInscription>2025-11-06</dateInscription>
                </membre>
                <membre id="M024">
                    <nom>BOUZABIA</nom>
                    <prenom>KHOULOUD</prenom>
                    <email>k.bouzabia@club.dz</email>
                    <dateInscription>2025-11-06</dateInscription>
                </membre>
                <membre id="M025">
                    <nom>KEHIT</nom>
                    <prenom>BOUCHRA</prenom>
                    <email>b.kehit@club.dz</email>
                    <dateInscription>2025-11-08</dateInscription>
                </membre>
                <membre id="M026">
                    <nom>MEGHERBI</nom>
                    <prenom>NOUHA</prenom>
                    <email>n.megherbi@club.dz</email>
                    <dateInscription>2025-11-10</dateInscription>
                </membre>
                <membre id="M027">
                    <nom>MEKSEN</nom>
                    <prenom>NADJIB</prenom>
                    <email>n.meksen@club.dz</email>
                    <dateInscription>2025-11-10</dateInscription>
                </membre>
                <membre id="M028">
                    <nom>BAGHA</nom>
                    <prenom>SADJEDA</prenom>
                    <email>s.bagha@club.dz</email>
                    <dateInscription>2025-11-12</dateInscription>
                </membre>
                <membre id="M029">
                    <nom>BOUCHEHIT</nom>
                    <prenom>WANASAH MERIEM</prenom>
                    <email>w.bouchehit@club.dz</email>
                    <dateInscription>2025-11-12</dateInscription>
                </membre>
                <membre id="M030">
                    <nom>BOUGHAZI</nom>
                    <prenom>ZAKARIA</prenom>
                    <email>z.boughazi@club.dz</email>
                    <dateInscription>2025-11-15</dateInscription>
                </membre>
                <membre id="M031">
                    <nom>BOUKHECHIMA</nom>
                    <prenom>HADJER</prenom>
                    <email>h.boukhechima@club.dz</email>
                    <dateInscription>2025-11-15</dateInscription>
                </membre>
                <membre id="M032">
                    <nom>DAHMRI</nom>
                    <prenom>CHEMS</prenom>
                    <email>c.dahmri@club.dz</email>
                    <dateInscription>2025-11-16</dateInscription>
                </membre>
                <membre id="M033">
                    <nom>DJOUAD</nom>
                    <prenom>WISSEM</prenom>
                    <email>w.djouad@club.dz</email>
                    <dateInscription>2025-11-18</dateInscription>
                </membre>
            </membres>
        </category>

        <category id="CAT03">
            <nomCategorie>Sécurité Informatique</nomCategorie>
            <membres>
                <membre id="M034">
                    <nom>FERHAT</nom>
                    <prenom>CHAIMA SIRINE</prenom>
                    <email>c.ferhat@club.dz</email>
                    <dateInscription>2025-11-20</dateInscription>
                </membre>
                <membre id="M035">
                    <nom>GRIMED</nom>
